/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_mozzie_mozlearning_agjni_MyJniTest */

#ifndef _Included_com_example_mozzie_mozlearning_agjni_MyJniTest
#define _Included_com_example_mozzie_mozlearning_agjni_MyJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mozzie_mozlearning_agjni_MyJniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mozzie_mozlearning_agjni_MyJniTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
